version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Update Repo Information
          command: apt-get update -qq

      - run:
          name: Install Python3 and Cmake
          command: apt-get install -qq -y cpio python3 python3-pip cmake

      - run:
          name: Install ISRM
          command: pip3 install http://rscohn2.github.io/files/isrm-master.zip

      - run:
          name: Install ICC
          command: isrm pkg install --activate-serial-number icc ifort

      - run:
          name: Build and Test Project
          command: source /opt/intel/bin/iccvars.sh -arch intel64 && 
                   icc -v && 
                   mkdir build; cd build && 
                   FC=ifort CC=icc CXX=icpc cmake ../src && 
                   make && 
                   make test
